package org.encrypteddb

import java.util

import com.typesafe.scalalogging.StrictLogging
import org.crypto.sse._
import org.encrypteddb.utils.FileUtils

import scala.collection.JavaConverters._

/**
  * * A EDB server, that holds secret key `sk` and generates update and search tokens
  */
class EDBServer(edb: util.HashMap[String, Array[Byte]]) extends FileUtils with StrictLogging {

  /**
    * Update EDB using the provided update token
    *
    * @param updateToken - update token generated by the client
    * @return Success on correct update, Failure otherwise
    */
  def insert(updateToken: InsertToken): Unit = {
    DynRH.update(edb, updateToken.token)
    logger.info(s"Server database updated with ${updateToken.token.keySet().size()} pairs")
  }

  /**
    * Find all documents using the provided search token
    *
    * @param token - search token, generated by the client
    * @return list of document ids
    */
  def search(token: SearchToken): List[String] = {
    DynRH.resolve(token.key2, DynRH.queryFS(token.token, edb)).asScala.toList
  }

}

object EDBServer {
  def create(): EDBServer = new EDBServer(DynRH.setup())
}
